### ISSUE TITLE
这段代码没有写共享变量，为什么要加锁呢？

### ISSUE THREAD

**Issue by Focus848** [kevin0571/STNetTaskQueue#10]
[这段代码没有写共享变量，为什么要加锁呢？](https://github.com/kevin0571/STNetTaskQueue/blob/master/STNetTaskQueue/STNetTaskQueue.m#L232)

**Comment by kevin-lyn** [comment]
@Focus848 因为这里只是简单地用了Recursive Lock，所以无论读写都要加锁。如果想要优化这里，可以用读写锁，这样读操作可以并行，只有写操作会锁。但是这里的性能不是很敏感，所以就用最简单的方法实现了。关于读写锁，Obj-C 里可以用 pthread 或者 GCD 来做。

**Comment by Focus848** [comment]
@kevin0571 谢谢解答，iOS小白，看你的代码学了一些知识，很感谢。
