### ISSUE TITLE
添加removeTaskDelegate: uri:方法

### ISSUE THREAD

**Issue by lhyhsx** [kevin0571/STNetTaskQueue#2]
新闻类的应用(如下图)，在每个管理新闻列表的控制器中都会调用获取新闻列表的接口.在来回切换不同的新闻类别时，会将多个delegate添加到同一个uri下。这样在每个新闻列表控制器中调用获取新闻列表的接口时，多个新闻列表控制器实列的代理方法都会被调用.
所以需要添加一个移除代理的方法（`removeTaskDelegate: uri:`)，在获取新闻列表成功后，将代理移除.

![252d9c5d-fbef-4117-8f37-430a65973f61](https://cloud.githubusercontent.com/assets/9956247/10009723/adbc2722-6113-11e5-9915-4437ee9d8ed9.png)

**Comment by kevin-lyn** [comment]
@lhyhsx 在没有removeDelegate的情况下，可以尝试每个控制器持有一个task的property，在netTaskDidEnd的逻辑里判断如果 task != self.task 就直接返回。

**Comment by lhyhsx** [comment]
@kevin0571 谢谢回复。哪样不行呢，因为每一个新闻列表都是`同一个控制器的不同实例`，执行的是同一段代码.
我加了个方法

```
- (void)removeTaskDelegate:(id<STNetTaskDelegate>)delegate uri:(NSString *)uri {
    NSMutableArray *delegates = [self.taskDelegates objectForKey:uri];
    if (delegates) {
        for (STNetTaskDelegateWeakWrapper *weakWrapper in delegates) {
            if (weakWrapper.delegate == delegate) {
                [delegates removeObject:weakWrapper];
                break;
            }
        }
    }
}
```

然后在`netTaskDidEnd`里调用这个方法，现在程序工作正常了。

**Comment by kevin-lyn** [comment]
Fixed in 0.0.9
