### ISSUE TITLE
Undefined content type for a FormData request type

### ISSUE THREAD

**Issue by osorochich** [kevin0571/STNetTaskQueue#5]
Hi!

First of all I'd like to say thank you for this great lib. I've used it in my recent projects and we love how it works.

Actually, we faced with one issue regarding `FormData` request type and `Content-Type`  header.
I've changes `STHTTPNetTaskContentTypeMap` initialization to be like this: 

`STHTTPNetTaskContentTypeMap = @{ 
@(STHTTPNetTaskRequestJSON): @"application/json; charset=utf-8",
@(STHTTPNetTaskRequestKeyValueString): @"application/x-www-form-urlencoded", @(STHTTPNetTaskRequestFormData) : @"application/x-www-form-urlencoded"};`

After that our problem was go away. Maybe you know another workaround regarding this?
Because, we need to set `HTTP-header` for `Content-Type` for all our requests.

Thanks is advance!

**Comment by kevin-lyn** [comment]
@osorochich Glad to hear that you love the library.
One of the best practices of using STNetTask would be create a base net task for each project/module.
You can create a base net task and then implement the "headers" method, which will return a NSDictionary to specify your custom HTTP headers.
I've pushed a fix to make sure "Content-Type" can be overwritten in custom headers.
If you want to return "application/x-www-form-urlencoded" only for form data request, it could be:

``` objc
- (NSDictionary *)headers
{
    if (self.requestType == STHTTPNetTaskRequestFormData) {
        return @{ @"Content-Type": @"application/x-www-form-urlencoded" };
    }
    return nil;
}
```

Don't know why you need to set form data request with content type "application/x-www-form-urlencoded". Most of the time it should be "multipart/form-data".

**Comment by osorochich** [comment]
@kevin0571 thanks a lot for the quick reply. Yes, we use the library exactly the same as you've described above :)
And thank you for the fix! Now it should work great.
We need to set  "application/x-www-form-urlencoded" because of our backend team require us to do this. I believe it is backend services implementation details.
